Repository rafalino26/front-end-warongwarem, pull requests merged in 2023-12, with the labels that each got.

#2 feat: Landing and login page
  package-lock.json
  package.json
  public/glass.jpg
  public/marker.jpg
  public/marker.png
  public/marker1.jpg
  src/App.css
  src/App.jsx
  src/Components/LPcoms.jsx
  src/Components/SignAs.jsx
  src/Components/SignAsCustomer.jsx
  src/Components/SignAsManager.jsx
  src/Components/SignAsWaiters.jsx
  src/Components/Signupcoms.jsx
  src/Pages/Home.jsx
  src/Pages/SigninAs.jsx
  src/Pages/Signup.jsx
  src/Pages/signinAsCustomers.jsx
  src/Pages/signinAsManagers.jsx
  src/Pages/signinAsWaiters.jsx
Labels: enhancement

#4 feat: Customer Home Page
  src/App.css
  src/App.jsx
  src/Components/CustComs.jsx
  src/Components/SignInComs.jsx
  src/Pages/CustomerDashboard.jsx
Labels: enhancement

#6 feat: signup api integration etc
  package-lock.json
  package.json
  src/App.css
  src/Components/ContactComs.jsx
  src/Components/CustComs.jsx
  src/Components/HistoryComs.jsx
  src/Components/Signupcoms.jsx
Labels: bug, enhancement

#8 feat: default value for users
  src/Components/Signupcoms.jsx
Labels: enhancement

#9 feat: error-message
  src/App.css
  src/Components/CustComs.jsx
  src/Components/SignInComs.jsx
  src/Components/Signupcoms.jsx
Labels: enhancement

#10 feat: Staff Signup Page
  public/date.png
  public/person.png
  public/table.png
  src/App.css
  src/App.jsx
  src/Components/HistoryComs.jsx
  src/Components/SignupMWcoms.jsx
  src/Pages/SignupMW.jsx
Labels: enhancement

#13 feat sigin in integration
  src/App.css
  src/Components/SignInComs.jsx
  src/Components/Signupcoms.jsx
Labels: enhancement

#14 feat: booking integration
  package-lock.json
  package.json
  src/App.css
  src/Components/CustComs.jsx
  src/Components/ReservationComs.jsx
Labels: enhancement

#15 feat: page animation
  src/Components/AboutComs.jsx
  src/Components/ContactComs.jsx
  src/Components/CustComs.jsx
  src/Components/LPcoms.jsx
  src/Components/SignInComs.jsx
  src/Components/Signupcoms.jsx
Labels: enhancement

#16 fix: api integration
  src/App.css
  src/App.jsx
  src/Components/CustComs.jsx
  src/Components/ReservationComs.jsx
  src/Components/SignInComs.jsx
  src/Components/managercoms.jsx
  src/Pages/Managers.jsx
Labels: bug

#18 fix: design button
  src/App.css
  src/Components/managercoms.jsx
  src/Components/managerstablecoms.jsx
  src/Components/waitersdbcoms.jsx
  src/Components/waiterstablecoms.jsx
Labels: bug, enhancement

#19 feat: role dashboard case
  src/Components/SignInComs.jsx
Labels: enhancement

#20 fix: change navbar name
  src/App.css
  src/App.jsx
  src/Components/AboutComs.jsx
  src/Components/LPcoms.jsx
  src/Components/SignInComs.jsx
  src/Components/Signupcoms.jsx
  src/Pages/Managers.jsx
  src/Pages/ManagersTable.jsx
Labels: bug, enhancement

#22 fix: role definition
  src/Components/SignInComs.jsx
Labels: bug

#23 feat: date and time icon
  public/calendar1.png
  public/time1.png
  src/App.css
  src/Components/managercoms.jsx
Labels: enhancement

#24 feat: reservation integration
  src/App.css
  src/Components/ReservationComs.jsx
  src/Components/waitersdbcoms.jsx
Labels: enhancement

#25 feat: change to deployed link
  src/Components/CustComs.jsx
  src/Components/SignInComs.jsx
  src/Components/Signupcoms.jsx
Labels: enhancement

#26 fix: reservation api
  src/Components/CustComs.jsx
Labels: bug
